### ISSUE TITLE
RE: Does This MRAA and UPM Work Out-of-the-Box with Kernel 4.9/Stretch?

### ISSUE THREAD

**Issue by silver2row** [Pillar1989/mraa#5]
Hello,

I was wondering how I could use this MRAA and UPM modules with my Grove Cape v2. I tried to use some software but it keeps coming back with cannot find module 'jsupm_grovegprs'

What should I do to try this software out?

Seth

**Comment by RobertCNelson** [comment]
@silver2row it's actually nodejs.  In Jessie, this was built against v0.12.x, that's why when we switched to nodejs v4.x, the seeed images still used v0.12.x as the base.  In stretch, we are using v6.x by default, so mraa/upm will have to be re-built against that.

Regards,

**Comment by silver2row** [comment]
Hello,

Are there any books on rebuilding mraa/upm? If there are not any books, what resources are out there for rebuilding the mraa/upm modules?

Seth

**Comment by Pillar1989** [comment]
Yes，you can

**Comment by silver2row** [comment]
Hello Pillar,

Thank you for this input. I will try it out. I will probably have issues but if not, good times!

Seth

**Comment by silver2row** [comment]
Hello Again Pillar,

Seth here. Can I use SWIG and the other mentioned downloads from my BBB or do I have to have an Arm MCU with more space?

Seth
